# Generated by Django 4.1.6 on 2023-03-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('users', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('emaill', models.CharField(max_length=20)),
                ('comments', models.TextField(max_length=400)),
            ],
            options={
                'db_table': 'Reviews',
            },
        ),
    ]
