# Generated by Django 4.1.6 on 2023-03-27 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='ReviewsRate',
        ),
        migrations.AlterModelTable(
            name='reviewsrate',
            table='ReviewsRate',
        ),
    ]
