# Generated by Django 4.1.6 on 2023-03-28 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_rename_reviews_reviewsrate_alter_reviewsrate_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewsRate',
        ),
    ]
