# Generated by Django 4.1.6 on 2023-04-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_delete_reviewsrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namee', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Reviews',
            },
        ),
    ]
